project:
  type: book
  output-dir: docs

book:
  title: "A book using quarto"
  site-url: https://oojdoo.github.io/book-quarto/
  author: "Norah Jones"
  date: "17/06/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - graphiques.qmd
    - summary.qmd
    - references.qmd

  downloads: [pdf, docx]
  sidebar:
    pinned: true
    background: AliceBlue
  search: true
  repo-url: https://github.com/oojdoo/book-quarto
  repo-branch: main
  repo-actions: [source]


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx: default



