project:
  type: book
  output-dir: docs

book:
  title: "A book using quarto"
  author: "Norah Jones"
  date: "17/06/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

  downloads: [pdf]
  sidebar:
    pinned: true


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



